include:
  - local: "/ci/includes/java.yml"
  - project: $CATALOG_PATH
    file:
      - vault-ci.yml
      - kaniko-ci.yml
    ref: main

default:
  image: alpine:latest
#  tags:
#    - ADD_CUSTOM_TAG_HERE

cache:
  paths:
    - .m2/repository/
    - node_modules

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  DOCKERFILE: Dockerfile
  PROJECT_PATH: ${PROJECT_ORGANISATION}-${PROJECT_NAME}
  REGISTRY_URL: "${IMAGE_REPOSITORY}"


stages:
  - read-secret
  - build-app
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

package-app:
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
    MAVEN_CLI_OPTS: ""
    MVN_CONFIG_FILE: $MVN_CONFIG
    BUILD_IMAGE_NAME: maven:3.8-openjdk-17
    WORKING_DIR: .
    ARTEFACT_DIR: ./target/*.jar

  stage: build-app
  extends:
    - .java:build

docker-build:
  variables:
    WORKING_DIR: "."
    IMAGE_NAMES: mail-demo:1.0.0
  stage: docker-build
  extends:
    - .kaniko:build-push
